param(
    [Parameter(Mandatory=$true)][String] $dir,
    [Parameter(Mandatory=$true)][String] $persist_dir
)

# --- Define the content of the single Batch Wrapper File ---
# NOTE: The content uses the Batch variables (%~dp0, %0, etc.) for fast runtime execution.
$wrapperContent = @"
@echo off
REM =======================================================
REM | Fast Batch Wrapper for Isolated PHP Version         |
REM | Generated by create-wrapper.ps1                     |
REM =======================================================

REM Set the isolated PHP config directories for this version.
REM Uses %~dp0 to reliably point to the current installation directory ($dir).
SET PHP_INI_SCAN_DIR=%~dp0\cli;%~dp0\cli\conf.d

REM Get the command used to call this script (e.g., 'php84', 'php84-cgi')
FOR %%I IN ("%0") DO SET "CALLER_NAME=%%~nI"

REM --- Routing Logic ---
IF /I "%CALLER_NAME%" EQU "php84-cgi" GOTO CGI
IF /I "%CALLER_NAME%" EQU "php84dbg" GOTO DBG

REM Default: php.exe (for alias 'php84')
"%~dp0\php.exe" %*
GOTO END

:CGI
REM Run php-cgi.exe
"%~dp0\php-cgi.exe" %*
GOTO END

:DBG
REM Run phpdbg.exe
"%~dp0\phpdbg.exe" %*
GOTO END

:END
"@

# Output the script to the installation folder ($dir)
$wrapperContent | Out-File "$dir\php-wrapper.cmd" -Encoding UTF8

Write-Host "✅ Generated smart PHP wrapper: $dir\php-wrapper.cmd"
